networks:
  external-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
  local-network:
    external: false

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./docker/db/data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: "overlay"
      o: "lowerdir=${PWD}/docker/wordpress,upperdir=${PWD}/src/wordpress,workdir=${PWD}/docker/overlay/wordpress"
      device: "overlay"
  woonuxt_data:
    driver: local
    driver_opts:
      type: "overlay"
      o: "lowerdir=${PWD}/docker/woonuxt,upperdir=${PWD}/src/woonuxt,workdir=${PWD}/docker/overlay/woonuxt"
      device: "overlay"

services:
  mysql:
    image: ${MYSQL_IMAGE_TAG}
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql:rw
    user: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      external-network:
        ipv4_address: 172.28.0.2
    ports:
      - "127.0.0.1:3306:3306"
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "172.28.0.2",
          "-P",
          "3306",
          "-u${MYSQL_USER}",
          "-p${MYSQL_PASSWORD}",
        ]

      interval: 8s
      timeout: 2s
      retries: 3

  wordpress:
    image: ${WORDPRESS_IMAGE_TAG}
    container_name: wordpress-crm
    volumes:
      - wordpress_data:/var/www/html
    networks:
      external-network:
        ipv4_address: 172.28.0.3
    ports:
      - "80:80"
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1
      interval: 8s
      timeout: 2s
      retries: 3
      start_period: 90s
    depends_on:
      mysql:
        condition: service_healthy

  # woonuxt:
  #   image: ${WOONUXT_IMAGE_TAG}
  #   container_name: woonuxt
  #   env_file: .env
  #   working_dir: /var/www
  #   volumes:
  #     - woonuxt_data:/var/www
  #   command: bash -c "npm install && npm run dev"
  #   networks:
  #     external-network:
  #       ipv4_address: 172.28.0.4
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     wordpress:
  #       condition: service_healthy
